// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "autoLookupEnabled": boolean;
      "writeCacheToExtra": boolean;
      "minMatchScore": number;
      "showAbbrColumn": boolean;
      "enableDebugLog": boolean;
      "customAliasRules": string;
    };
  }
}
